<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Console_Table' => $vendorDir . '/pear/console_table/Table.php',
    'PHP_Invoker' => $vendorDir . '/phpunit/php-invoker/src/Invoker.php',
    'PHP_Invoker_TimeoutException' => $vendorDir . '/phpunit/php-invoker/src/TimeoutException.php',
    'PHP_Timer' => $vendorDir . '/phpunit/php-timer/src/Timer.php',
);
